### ISSUE TITLE
client.zones.start not working

### ISSUE THREAD

**Issue by billbrazeal** [bachya/regenmaschine#7] opened 2017-07-13 02:42 UTC
This code is very helpful as I have just gotten a rainmachine and am needing to program to it.  I have gotten the python code installed and tested out.  Everything seems to be working except for the zones.start command.  I can even run programs.start successfully so there seems to be a bug in the zones.start code.  Can you check that to see what the problem is?

I get the following traceback on the client.zones.start command:

Traceback (most recent call last):
  File "Untitled 3.py", line 45, in <module>
    client.zones.start(3, 300)
  File "/Library/Python/2.7/site-packages/regenmaschine/zone.py", line 47, in start
    seconds}).object.json()
  File "/Library/Python/2.7/site-packages/regenmaschine/api.py", line 105, in post
    return self.request('post', api_endpoint, **kwargs)
  File "/Library/Python/2.7/site-packages/regenmaschine/api.py", line 96, in request
    response.raise_for_status()
  File "/Library/Python/2.7/site-packages/regenmaschine/api.py", line 34, in raise_for_status
    self.object.raise_for_status()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://192.168.0.2:8080/api/4/zone/3/start?access_token=f03598125bfa574948e88b5eb5bd9d76087271e92ad3cb2cc8748649

**Comment by bachya** [comment] 2017-07-13 04:01
Sorry to hear you're having trouble, @billbrazeal. Can you confirm that you're calling the function correctly (per the docs)? Should look something like:

```python
client.zones.start(<zone_id>, <number_of_seconds_to_run>
```

If that isn't the problem, try opening a terminal and starting the program directly via your local device's API:

```bash
$ curl -X "POST" "https://192.168.0.2:8080/api/4/zone/3/start?access_token=f03598125bfa574948e88b5eb5bd9d76087271e92ad3cb2cc8748649" \
     -H "Cookie: access_token=f03598125bfa574948e88b5eb5bd9d76087271e92ad3cb2cc8748649" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d $'{
  "time": 60
}'
```

Let me know the results!

**Comment by billbrazeal** [comment] 2017-07-13 04:09
I do hae the syntax correct for the start command.

When I try the curl command I get the following - curl: (60) SSL certificate problem: Invalid certificate chain

Should I replace the access_token with something different?  I just copied what you had in your post and it didn't work.

**Comment by billbrazeal** [comment] 2017-07-13 04:22
It does seem odd to me that in the same python script I can run the client.programs.start(1) command and it runs fine then when hit the line that runs client.zones.start(1, 300) it fails.  Seems like it may be a bug.

**Comment by bachya** [comment] 2017-07-13 04:38
Maybe; it works fine on my local device. Try adding - `-k` to that cURL request ) to disable certificate validation) and run it one more time.

**Comment by billbrazeal** [comment] 2017-07-13 04:42
The -k did the trick and that works. How can I make that work in the python
script?

<http://billbrazeal.com/> <bill@billbrazeal.com>
<bill@billbrazeal.com> <https://twitter.com/#!/billbrazeal>
<https://www.facebook.com/billbrazeal.public>
<http://www.linkedin.com/pub/bill-brazeal/35/688/baa> <skype:bbrazeal?call>
<http://www.youtube.com/user/bbrazeal1>
<http://feeds.feedburner.com/billbrazeal/LatestBlogs>
<bbrazeal@eznetllc.com>.

On Jul 12, 2017, at 11:38 PM, Aaron Bach <notifications@github.com> wrote:

Maybe; it works fine on my local device. Try adding - -k to that cURL
request ) to disable certificate validation) and run it one more time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bachya/regenmaschine/issues/7#issuecomment-314968575>,
or mute the thread

**Comment by bachya** [comment] 2017-07-13 04:46
Not sure yet; I don't see anything off. Dump as much information about your environment here: Python version, RainMachine version, operating system you're running this on, etc.

**Comment by billbrazeal** [comment] 2017-07-13 04:46
Will do. Thanks!

<http://billbrazeal.com/> <bill@billbrazeal.com>
<bill@billbrazeal.com> <https://twitter.com/#!/billbrazeal>
<https://www.facebook.com/billbrazeal.public>
<http://www.linkedin.com/pub/bill-brazeal/35/688/baa> <skype:bbrazeal?call>
<http://www.youtube.com/user/bbrazeal1>
<http://feeds.feedburner.com/billbrazeal/LatestBlogs>
<bbrazeal@eznetllc.com>.

On Jul 12, 2017, at 11:46 PM, Aaron Bach <notifications@github.com> wrote:

Not sure yet; I don't see anything off. Dump as much information about your
environment here: Python version, RainMachine version, operating system
you're running this on, etc.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bachya/regenmaschine/issues/7#issuecomment-314969450>,
or mute the thread

**Comment by billbrazeal** [comment] 2017-07-13 04:59
The rainmachine device is a new mini-8 running firmware 4.0.900.  I am running python 2.7 on macos 10.11.6 El Capitan.  I am

**Comment by bachya** [comment] 2017-07-13 20:57
I was able to reproduce! I'll get working on a bugfix and get back to you. Thanks!

**Comment by bachya** [comment] 2017-07-13 22:15
@billbrazeal: Just released v0.3.1, which fixes this issue. Going to close this issue; let me know if you run into any problems!

**Closed by bachya** 2017-07-13 22:15 UTC
Labels: bug

**Comment by billbrazeal** [comment] 2017-07-14 13:59
Thank You @bachya !  I will check it out.  I really appreciate you looking into this and fixing.

**Comment by billbrazeal** [comment] 2017-07-14 14:09
Thanks so much for fixing the code.  I have tested it out and it works perfectly!

Just curious, what was the issue?

Bill
 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-07-14 15:32
@billbrazeal: Glad to hear!

The underlying HTTP request library is [Requests](https://github.com/requests/requests). It turns out that by default, sending data in a request body (like `zones.start` does) was defaulting to a format like this:

```
time=60
```

...when the RainMachine API was expecting a JSON format:

```
{"time": 60}
```

Once I made that change, everything started working!

**Comment by bachya** [comment] 2017-07-14 23:30
@billbrazeal: Wondering if you could give me a little feedback. I'm considering a change (#6) that would require users of my library to have a Python version greater than or equal to 3.4.2. I believe you mentioned above that you have 2.7 – would it be prohibitive for you to upgrade? Since you are my user base at the moment, want to make sure you're covered. :)

**Comment by billbrazeal** [comment] 2017-07-16 21:53
Hey Aaron, yes I use 2.7 primarily but I think I have python 3.x loaded as
well. I don't really know that much about python but can't I have both
loaded and when I need to, run python3 for specific scripts that run 3.x
code and just regular python for 2.7?  If so that would work for me. I
probably would not want to move exclusively to 3.x for all my scripts if
that were required. If that was the case I would prefer both versions
remain supported.

Thanks for reaching out.

Bill

<http://billbrazeal.com/> <bill@billbrazeal.com>
<bill@billbrazeal.com> <https://twitter.com/#!/billbrazeal>
<https://www.facebook.com/billbrazeal.public>
<http://www.linkedin.com/pub/bill-brazeal/35/688/baa> <skype:bbrazeal?call>
<http://www.youtube.com/user/bbrazeal1>
<http://feeds.feedburner.com/billbrazeal/LatestBlogs>
<bbrazeal@eznetllc.com>.

On Jul 14, 2017, at 6:30 PM, Aaron Bach <notifications@github.com> wrote:

@billbrazeal <https://github.com/billbrazeal>: Wondering if you could give
me a little feedback. I'm considering a change (#6
<https://github.com/bachya/regenmaschine/issues/6>) that would require
users of my library to have a Python version greater than or equal to
3.4.2. I believe you mentioned above that you have 2.7 – would it be
prohibitive for you to upgrade? Since you are my user base at the moment,
want to make sure you're covered. :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bachya/regenmaschine/issues/7#issuecomment-315490653>,
or mute the thread

**Comment by billbrazeal** [comment] 2017-08-14 15:13
Aaron, I have a question for you since I am sure you have spent a lot of time working with the rainmachine device.

Your code for me is working fine.  However, I have begun to notice that the rainmachine device itself has started shutting down its ip access.  When I reboot it, I can ping it via its ip address but then after about a minute it no longer responds which also means I cannot authenticate to it or run any of the python script commands against it.  

I can still access it via the iOS app so I know it is still working but it seems to have shut down the ip access for some reason.

Have you noticed this behavior as you have worked with the rainmachine before?  If so, how can I fix it?  Or should I just contact rainmachine support directly?

Thanks,

Bill 
 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by billbrazeal** [comment] 2017-08-14 15:19
Also, this just started happening since about August 11 or 12 and the software version on the rain machine is 4.0.900.  It seems to be the most current version.  Not sure if that gets updated automatically or if I have to update it but I have not updated software version manually at least for a month or so.

Thanks,

Bill
 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-08-14 15:22
Hi @billbrazeal – which RainMachine do you have? I had a Mini-8 that started acting up about 2-3 months in: would lose its wifi connection, reboot endlessly, until finally, it wouldn't turn on at all. RainMachine ended up swapping it out.

Check out my support ticket: https://support.rainmachine.com/hc/en-us/requests/16619 – does this mirror what you're experiencing?

**Comment by billbrazeal** [comment] 2017-08-14 15:27
It is a mini-8.  It is working via the iOS app but that is all.  I just tried it with an alexa command and that does not work either.  Sounds like it may be a hardware issue. 

I cannot see your support ticket but I guess I will start working with their support.

Do you have any other models?  Do they seem to be working better?

Thanks,

Bill 
 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-08-14 17:58
Ah, okay – I had a Mini-8, too, and they ended up replacing it. I would reach out to them.

**Comment by billbrazeal** [comment] 2017-08-15 16:40
Just to follow up on the mini-8 communication issue, it appears it is a switch problem that was preventing the IP from passing through which was blocking communications to the rain machine.  I had updated the firmware on the router over the weekend and that seems to be the cause.

On another note, where is the best place to put your python code.  I am noticing it takes about 5 seconds to import the code causing the program to delay a bit before it starts.  I would like to make it as efficient and quick as possible.  What do you recommend to make it load and run fastest?  I am running it on a mac if that makes a difference.

For your info, I am using your code to programmatically start a sprinkler zone based on movement I sense via my security cameras to scare off deer.  We have a big problem with deer eating our flowers and plants so this works really well.  But, the faster I can invoke the program and it starts the sprinklers, the better it works. :)

Thanks,

Bill
 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-08-15 16:46
@billbrazeal: Do you find that this delay occurs at the very beginning, when you're creating an `Authenticator` object? Or does it happen elsewhere?

**Comment by billbrazeal** [comment] 2017-08-15 16:49
It is just at the beginning when it seems that the import is happening.  When I actually run the authentication and commands they run fast.

 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-08-15 17:03
Interesting. When I import the library, it takes max 1 second.

One thought is that authentication can take time because, by default, the library is requesting a new API token each time the `Authenticator` is instantiated. You might consider caching that info in your own code; some thoughts: http://bachya.github.io/regenmaschine/guide/advanced.html#authentication-caching

**Comment by billbrazeal** [comment] 2017-08-15 17:27
ok, I will take a look.  But, where should I place your python library because I have seen there are a number of places to install it.  I am fairly new to python so I wouldn’t be surprised if I am doing something wrong.

Thanks,

 <http://billbrazeal.com/>	 <mailto:bill@billbrazeal.com>
 <mailto:bill@billbrazeal.com>	 <https://twitter.com/#!/billbrazeal>	 <https://www.facebook.com/billbrazeal.public>	 <http://www.linkedin.com/pub/bill-brazeal/35/688/baa>	 <skype:bbrazeal?call>	 <http://www.youtube.com/user/bbrazeal1>	 <http://feeds.feedburner.com/billbrazeal/LatestBlogs> <mailto:bill@billbrazeal.com>

**Comment by bachya** [comment] 2017-08-15 18:31
The easiest way to install the library is via `pip`: http://bachya.github.io/regenmaschine/guide/installation.html#using-pip

Once installed, any Python script you have should have access to the library.

(once you get comfortable, you might want to check out [virtualenv](https://virtualenv.pypa.io/en/stable/))
